version '3'

services:

    react:
        build: .
        container_name: react-app
        privileged: true
        restart: always
        ports:
            - 3000:3000
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
